# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - lumber-spine-medsrgan

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://medsrgan.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_f620c2c1d0a645e1b780157a500a80d3 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_747056c88c6343fda3df9e791a4f86b3 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: medsrgan.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_f620c2c1d0a645e1b780157a500a80d3 }}/med_srgan:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'lumber-spine-medsrgan'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_8efc9d31ad394043bd07b92ce790a0fb }}
        images: 'medsrgan.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_f620c2c1d0a645e1b780157a500a80d3 }}/med_srgan:${{ github.sha }}'